### ISSUE TITLE
sniblocking: allow DoT/DoH domain resolution

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#392]
The current implementation assumes a standard resolver. If we ever use DoT/DoH, then we likely need to separate the DoT/DoH step from the proper measuring step, otherwise the heuristics introduced in https://github.com/ooni/probe-engine/pull/391 to classify the results may be confused.

**Comment by bassosimone** [comment]
This is mostly done. In Sprint 12, I introduced the `urlgetter` experiment that can do that. So now the next step is to rewrite `sniblocking` as two calls to `urlgetter`. Then this property will be available to users running the experiment. (I also think we should not use the system resolver when running this experiment, and I am investigating that w/ https://github.com/bassosimone/aladdin)

**Comment by bassosimone** [comment]
## Implementation plan

- [ ] Add the proper `Config.ResolveURL` field to `/experiment/sniblocking` copying what we do in `/experiment/urlgetter`
- [ ] Make sure that we pass such field to `urlgetter` when we invoke it from `sniblocking`
- [ ] Write some tests for this functionality (if I'm not doing this, then please let's have a convo about that)
