### ISSUE TITLE
netx: wrap up refactoring effort and create follow-ups

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#745]
Following up from https://github.com/ooni/probe-engine/issues/725. This refactoring has been lingering for quite some time now and in particular the related epic (https://github.com/ooni/probe-engine/issues/359) is now becoming old and I am worrying that we may start losing the original context. So, the following list of action items describes what needs to be done for calling the epic itself closed _but_ make sure we don't loose next steps.

- [x] move old `/netx` code to `/netx/legacy` (done in https://github.com/ooni/probe-engine/pull/884)
- [x] create issue for reimplementing `experiment/tor` in terms of `experiment/urlgetter`: it's https://github.com/ooni/probe-engine/issues/897
- [x] mention the original DESIGN in https://github.com/ooni/probe-engine/issues/359
- [x] can we avoid using the context for counting bytes? if not, document in https://github.com/ooni/probe-engine/issues/359 why perhaps? [update: it's clearly mentioned so nothing to do here]

This refactoring has been functional to measure performance metrics. In turn, by doing that we have been able to measure HTTP fetching performance metrics for Psiphon. This has also been key to rewrite Web Connectivity in Go.

**Comment by bassosimone** [comment]
This whole netx refactoring effort is coming to an end in Sprint 21. We have clearly refactored the code such that the new implementation is in `/netx` and the legacy (working correctly albeit more complex) implementation is in `/legacy/netx`. As such, the original text of this issue is now outdated and we should make sure the going-forward plan is clear.

**Comment by bassosimone** [comment]
Executed the above TODO list. It's fine to close this issue now.
