### ISSUE TITLE
Psiphon in probe-engine

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#89]
The Psiphon test is fully integrated inside of probe-engine making it ready for deployment.

The steps required are:

- [x] httpx implement NewClientWithProxy (ooni/netx#130)
- [x] HTTPDoConfig: add support for proxy function (ooni/netx#131)
- [x] porcelain: add proxy and byte counting support (ooni/netx#137)
- [x] build.sh: re-enable psiphon (ooni/probe-cli#79)
- [x] x/logger: mimic cURL logging (ooni/netx#137)
- [x] psiphon: use netx so we fill the HTTP template (ooni/probe-engine#129)
- [x] psiphon: make sure data format matches old implementation (ooni/probe-engine#128)
- [x] psiphon: make sure we're using latest version of dependencies (ooni/probe-engine#141)
- [x] orchestra: implement authenticated requests (ooni/probe-engine#148)
- [x] psiphon: fetch config via authenticated orchestra (ooni/probe-engine#109)
- [x] psiphon: use config from orchestra (ooni/probe-engine#167)
- [x] orchestra: MK compatible platform names (ooni/probe-engine#169)
- [x] orchestra: store login and tokens on persistent storage (ooni/probe-engine#164)
- [x] psiphon: follow-up of fetching config from orchestra (ooni/probe-engine#168)

**Comment by hellais** [comment]
@bassosimone can you add here a checklist of what are the next steps for getting this deployed?

I believe we now have the psiphon test inside of probe-engine, but building is disabled in probe-cli as we didn't want to include it for the stable release.

**Comment by bassosimone** [comment]
@hellais here's what I currently have sketched out:

- [x] httpx implement NewClientWithProxy (ooni/netx#130)
- [x] HTTPDoConfig: add support for proxy function (ooni/netx#131)
- [x] porcelain: add proxy and byte counting support (ooni/netx#137)
- [ ] x/logger: mimim cURL logging (ooni/netx#137)
- [ ] psiphon: use netx so we fill the HTTP template (ooni/probe-engine#128)
- [ ] psiphon: make sure data format matches old implementation (ooni/probe-engine#129)
- [ ] psiphon: fetch config via authenticated orchestra (ooni/probe-engine#109)

**Comment by bassosimone** [comment]
This is done!
